# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170119_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotografia',
            field=models.ImageField(default='TV/userDefault.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
