# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170119_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fotografia',
            field=models.ImageField(default='static/userDefault.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
