# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170119_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
