# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170119_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_de_nacimiento',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fotografia',
            field=models.ImageField(blank=True, default='/userDefault.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
