# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Deportes', 'Deportes'), ('Cultura', 'Cultura'), ('Música', 'Música'), ('Peliculas y series', 'Peliculas y series')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='canales/%Y/%m/%d/'),
        ),
    ]
