# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0003_auto_20170118_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canal',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
    ]
