# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0004_auto_20170119_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
