# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0005_canal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='logo',
            field=models.ImageField(upload_to='canales/%Y/%m/%d/'),
        ),
    ]
